server:
  addr: "127.0.0.1:8080"
  read_timeout: "10s"
  write_timeout: "0s"       # 建议 0，便于长时间流式回写
  idle_timeout: "120s"
redis:
  addr: "127.0.0.1:6379"
  db: 15
  password: "a~xnwgamrsZ/flqxyCjr:9vyml6yfn"
ansible:
  playbook: "/data/devops-ansible-misc"
  log: "/data/log/ansible-registration"
  user: "root"